AWSTemplateFormatVersion: "2010-09-09"
Resources:
  NatElasticIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: "vpc"
      Tags:
        - Key: "Name"
          Value: "NATEIP_lab_1"

  NATGateway:
    Type: "AWS::EC2::NatGateway"
    Properties:
      AllocationId: !GetAtt NatElasticIP.AllocationId
      SubnetId: !ImportValue PublicSubnetId
      Tags:
        - Key: "Name"
          Value: "NAT_lab_1"

  PrivateRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !ImportValue PrivateRouteTableId
      DestinationCidrBlock: "0.0.0.0/0"
      NatGatewayId: !Ref NATGateway

Outputs:
  NATGatewayId:
    Value: !Ref NATGateway
    Export:
      Name: NATGatewayId
