AWSTemplateFormatVersion: "2010-09-09"
Resources:
  PublicRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !ImportValue VPCId
      Tags:
        - Key: "Name"
          Value: "PublicRouteTable_lab_1"

  PublicRoute:
    Type: "AWS::EC2::Route"
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !ImportValue InternetGatewayId

  PublicRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !ImportValue PublicSubnetId
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !ImportValue VPCId
      Tags:
        - Key: "Name"
          Value: "PrivateRouteTable_lab_1"

  PrivateRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: !ImportValue PrivateSubnetId
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  PublicRouteTableId:
    Value: !Ref PublicRouteTable
    Export:
      Name: PublicRouteTableId
  PrivateRouteTableId:
    Value: !Ref PrivateRouteTable
    Export:
      Name: PrivateRouteTableId
