version: 0.2

phases:
  install:
    commands:
      - pip install cfn-lint taskcat
  pre_build:
    commands:
      - echo Pre-build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - cfn-lint modules/*.yaml || true
      - taskcat test run --input-file taskcat.yml
  post_build:
    commands:
      - echo Build completed on `date`
